Models/ErrorViewModel.cs
namespace ABM_Usuario.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Usuario.cs
using System;
using System.Collections.Generic;

namespace ABM_Usuario.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Usuario1 { get; set; } = null!;

    public string Contraseña { get; set; } = null!;

    public string? Nombre { get; set; }

    public string Apellido { get; set; } = null!;

    public string Direccion { get; set; } = null!;

    public DateTime? FechaNac { get; set; }

    public string Email { get; set; } = null!;

    public string? Telefono { get; set; }

    public string? Ciudad { get; set; }

    public string? CodigoPostal { get; set; }
}

Controllers/HomeController.cs
using ABM_Usuario.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace ABM_Usuario.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ABM_Usuario.Data;
using ABM_Usuario.Models;

namespace ABM_Usuario.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly FundacionContext _context;

        public UsuariosController(FundacionContext context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
              return _context.Usuarios != null ? 
                          View(await _context.Usuarios.ToListAsync()) :
                          Problem("Entity set 'FundacionContext.Usuarios'  is null.");
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Usuarios == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Usuario1,Contraseña,Nombre,Apellido,Direccion,FechaNac,Email,Telefono,Ciudad,CodigoPostal")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Usuarios == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Usuario1,Contraseña,Nombre,Apellido,Direccion,FechaNac,Email,Telefono,Ciudad,CodigoPostal")] Usuario usuario)
        {
            if (id != usuario.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Usuarios == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.Id == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Usuarios == null)
            {
                return Problem("Entity set 'FundacionContext.Usuarios'  is null.");
            }
            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario != null)
            {
                _context.Usuarios.Remove(usuario);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
          return (_context.Usuarios?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container mt-5">
        <div class="row justify-content-center">
        <div class="col-md-6" col-md-8">
            <div class="card">
                <img class="card-img-top" src="~/PBELTRAN.jpg" alt="Card image cap">
            <div class="card-body text-center">
                <h5 class="card-title">Pablo Ariel Beltrán</h5>
                <p class="card-text">Estudiante de Analista de Sistemas, 3° año. Primer exámen de Programación V, tema ASP.Net MVC</p>
                <a class="btn btn-primary" asp-controller="Usuarios" asp-action="Index">ABM Usuario</a>
            </div>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ABM_Usuario</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ABM_Usuario.styles.css" asp-append-version="true" />
    <!--Aca agrego un link nuevo-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <div>
                    <a href="http://superiorlapaz.edu.ar/" class="text-dark me-3" target="_blank">
                        
                        <img src="~/lapaz.ico" alt="Superior La Paz" style="height: 40px;">
                        
                    </a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Home</a>
                            <!--<a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>-->
                        </li>
                        <!--<li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>-->                     
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    &copy; 2024 - AMB Usuarios <a href="https://www.linkedin.com/in/bpariel/" class="text-dark"><i class="fab fa-linkedin"></i></a>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!--Aqui agrego script nuevos para mejorar con bootstrap el header de mi pagina-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Usuarios/Create.cshtml
@model ABM_Usuario.Models.Usuario

@{
    ViewData["Title"] = "Create";
}

<div class="d-flex justify-content-center align-items-center my-4">
    <img src="~/hacker.png" alt="Icono" style="height: 60px; width: 60px; margin-right: 20px;" />
    <p class="mb-0">
        <h3> AMB Usuarios <span class="badge badge-secondary"></span></h3>
    </p>
</div>

<form asp-action="Create">
    <div class="form-group">
        <label asp-for="Usuario1" class="control-label"></label>
        <input asp-for="Usuario1" class="form-control" />
        <span asp-validation-for="Usuario1" class="text-danger"></span>
        
    </div>
    <div class="form-group">
        <label asp-for="Contraseña" class="control-label">Password</label>
        <input asp-for="Contraseña" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
        <span asp-validation-for="Contraseña" class="text-danger"></span>
        <small id="emailHelp" class="form-text text-muted">Nunca debe compartir la contraseña con nadie</small>
    </div>
    <div class="form-group">
        <label asp-for="Nombre" class="control-label"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Apellido" class="control-label"></label>
        <input asp-for="Apellido" class="form-control" />
        <span asp-validation-for="Apellido" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Direccion" class="control-label"></label>
        <input asp-for="Direccion" class="form-control" />
        <span asp-validation-for="Direccion" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FechaNac" class="control-label"></label>
        <input asp-for="FechaNac" class="form-control" />
        <span asp-validation-for="FechaNac" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Telefono" class="control-label"></label>
        <input asp-for="Telefono" class="form-control" />
        <span asp-validation-for="Telefono" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Ciudad" class="control-label"></label>
        <input asp-for="Ciudad" class="form-control" />
        <span asp-validation-for="Ciudad" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CodigoPostal" class="control-label"></label>
        <input asp-for="CodigoPostal" class="form-control" />
        <span asp-validation-for="CodigoPostal" class="text-danger"></span>
    </div>
    <div class="form-group text-center">
        <button type="submit" class="btn btn-success">
            <i class="fas fa-user-plus"></i> Alta de usuario
        </button>
    </div>
    
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Usuarios/Delete.cshtml
@model ABM_Usuario.Models.Usuario

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contraseña)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contraseña)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNac)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNac)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ciudad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ciudad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodigoPostal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodigoPostal)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Usuarios/Details.cshtml
@model ABM_Usuario.Models.Usuario

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Contraseña)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Contraseña)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNac)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNac)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ciudad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ciudad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodigoPostal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodigoPostal)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Usuarios/Edit.cshtml
@model ABM_Usuario.Models.Usuario

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Usuario</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Usuario1" class="control-label"></label>
                <input asp-for="Usuario1" class="form-control" />
                <span asp-validation-for="Usuario1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Contraseña" class="control-label"></label>
                <input asp-for="Contraseña" class="form-control" />
                <span asp-validation-for="Contraseña" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNac" class="control-label"></label>
                <input asp-for="FechaNac" class="form-control" />
                <span asp-validation-for="FechaNac" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ciudad" class="control-label"></label>
                <input asp-for="Ciudad" class="form-control" />
                <span asp-validation-for="Ciudad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodigoPostal" class="control-label"></label>
                <input asp-for="CodigoPostal" class="form-control" />
                <span asp-validation-for="CodigoPostal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Usuarios/Index.cshtml
@model IEnumerable<ABM_Usuario.Models.Usuario>

@{
    ViewData["Title"] = "Index";
}
<div class="d-flex align-items-center">
    <img src="~/programmer.png" alt="Icono" style="height: 60px; width: 60px; margin-right: 20px;" />
    <p class="mb-0">
        <a asp-action="Create" class="btn btn-success">
            <i class="fas fa-plus"></i> Nuevo usuario
        </a>
    </p>
</div>

<table class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Usuario1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contraseña)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaNac)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ciudad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CodigoPostal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Contraseña)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaNac)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ciudad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodigoPostal)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-success">Edit</a>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning">Details</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>